name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      services:
        postgres:
          image: postgres:14
          env:
            POSTGRES_USER: pythonpro
            POSTGRES_PASSWORD: Pythonpro
            POSTGRES_DB: postgres
          ports: [ '5434:5432' ]

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.7
          architecture: x64
       cache: 'pip'
      - name: Copiar Configurações .env
        run: |
          cp contrib/.env-sample .env
      - name: Instalar dependências
        run: |
          pip install pipenv
          pipenv sync -d
      - name: Rodar flake8
        run: | 
          pipenv run flake8